version: '3'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=your_root_password
      - DB_NAME=your_database_name
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mariadb_data:
