name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Deploy Docker Images to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          echo "Pulling and running backend container"
          docker pull nongdev/product_management_backend:latest
          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend -p 8888:8888 nongdev/product_management_backend:latest
          
          echo "Pulling and running frontend container"
          docker pull nongdev/product_management_frontend:latest
          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 5000:5000 nongdev/product_management_frontend:latest
        EOF
      env:
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}