name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build and push backend Docker image
      run: |
        docker build -t nongdev/product_management_backend ./backend
        docker push nongdev/product_management_backend:latest

    - name: Build and push frontend Docker image
      run: |
        docker build -t nongdev/product_management_frontend ./frontend
        docker push nongdev/product_management_frontend:latest
